### ISSUE TITLE
Vendoring of gomega shouldn't result in compilation error

### ISSUE THREAD

**Issue by alexeits** [onsi/gomega#146] opened 2016-04-20 00:53 UTC
**Environment**
```
go version go1.6 darwin/amd64
```

**STR**
- Vendor gomega, for instance, using `godep`

    ```
    godep update github.com/onsi/gomega/...
   ```

- Run tests, for instance, using `ginkgo`

    ```
    ginkgo -r
    ```

**Result**
* Expected: tests should run
* Actual: compilation error:

    ```
    package github.com/sagansystems/cli/vendor/github.com/onsi/gomega
    	imports github.com/onsi/gomega/matchers
    	imports github.com/onsi/gomega/internal/oraclematcher: use of internal package not allowed

    ```

**Comment by robdimsdale** [comment] 2016-04-27 01:59
@alexeits we will need more information to debug this. I cannot reproduce simply by updating gomega in godeps. We do this all the time without issue.

The use of `internal` package is very odd, and leads me to believe the vendoring isn't working as expect - perhaps there's a mismatch between what's vendored and what's on your `GOPATH`.

I once saw a similar error when I had a typo in an import, leading go to get half of the packages from the `vendor` directory and half from the `GOPATH`.

**Comment by alexeits** [comment] 2016-04-27 04:40
@robdimsdale thanks for looking into this.

Your hunch about the mismatch of vendor vs. `GOPATH` was correct.

I ran some more experiments and determined that for some reason, contrary to godep [documentation](https://github.com/tools/godep#update-a-dependency) running just `godep update` was insufficient. 

I had to run `godep save ./...` as well.

**git status after running `godep update github.com/onsi/gomega/...`**
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Godeps/Godeps.json
	<snip>

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	vendor/github.com/onsi/gomega/matchers/and.go
	<snip>

```

**git status after running `godep save ./...`**
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Godeps/Godeps.json
	<snip>

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	vendor/github.com/onsi/gomega/internal/oraclematcher/ # <-- wasn't there after update
	vendor/github.com/onsi/gomega/matchers/and.go
	<snip>
```

That solved the issue.  Feel free to close.

Thank you very much for your help.

**Comment by robdimsdale** [comment] 2016-04-27 04:44
No problem - glad you were able to figure it out. For what it's worth, with the standardization of the `vendor` directory in go 1.6, some Pivotal / Cloud Foundry teams have found value in dropping godeps altogether - for reasons like this - and relying on git submodule instead.

Anyway, thanks for detailing your perspective on the issue and the corresponding resolution. I'm sure it'll prove helpful if others run into similar issues in the future. I'll close this now.

**Closed by robdimsdale** 2016-04-27 04:44 UTC
