### ISSUE TITLE
panic can't convert to string when use MatchRegexp

### ISSUE THREAD

**Issue by fanybook** [onsi/gomega#565] opened 2022-07-24 06:46 UTC
gomega version v1.19.0

official doc example: 
Expect(fn).Should(PanicWith(MatchRegexp(`.+Foo$`)))

but, panic can't convert to string (MatchRegexp -> toString(actual))
```
error output: 
PanicMatcher's value matcher failed with:
      RegExp matcher requires a string or stringer.
```

**Comment by thediveo** [comment] 2022-07-24 09:32
Hi there, 

which example do you refer to, this one?

```go
Ω(func() { panic("FooBarBaz") }).Should(PanicWith(MatchRegexp(`.+Baz$`)))
```

This example panics with a string. You don't show what your `fn` is, so might it panic with something that isn't a strong and also doesn't have a receiver function defined for conversion into string? Or did you shorten the example and the original example panics?

**Comment by thediveo** [comment] 2022-07-24 17:28
I've tried to reproduce the issue, but the documentation example works as it says on the tin (or rather, documentation). For reference, I created a module

```bash
go mod init gomegapanic
```

and then used this file `gomegapanic_test.go`:
```go
package gomegapanic

import (
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("panicking", func() {

	It("panics", func() {
		Expect(func() { panic("FooBarBaz") }).Should(PanicWith(MatchRegexp(`.+Baz$`)))
	})

})

func TestSessionPackage(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "playground")
}
```

and did `go test -v .`, which correctly passed.

```
=== RUN   TestSessionPackage
Running Suite: playground - /home/.../exp/gomegapanic
========================================================
Random Seed: 1658683495

Will run 1 of 1 specs
•

Ran 1 of 1 Specs in 0.000 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestSessionPackage (0.00s)
PASS
ok      gomegapanic     0.007s
```

**Comment by fanybook** [comment] 2022-08-11 02:49
@thediveo i panic a error, not a string

**Comment by thediveo** [comment] 2022-08-11 08:04
I can only guess here since you unfortunately do not provide a self-contained and reproducible example. Since you're now saying that you are panicking with an `error` type value, in consequence you need to additionally use an error-related matcher. Gomega's highly recommended online documentation describes the [MatchError](https://onsi.github.io/gomega/#matcherrorexpected-interface) as follows:

>     Ω(ACTUAL).Should(MatchError(EXPECTED))
> succeeds if ACTUAL is a non-nil error that matches EXPECTED. EXPECTED must be one of the following:
> - A string, in which case ACTUAL.Error() will be compared against EXPECTED.
> - A matcher, in which case ACTUAL.Error() is tested against the matcher.
> - [...]

My guess is that you need to correctly write the assumption as follows...

```go
Expect(func() { panic(errors.New("FooBarBaz")) }).Should(PanicWith(MatchError(MatchRegexp(`.+Baz$`))))
```

You need to be explicit here on purpose in order to avoid undetected and incorrect "convenience" conversions that in the end most of the time are incorrect and will introduce undetected bugs to the large existing test code base using Gomega.

Please report back if that solves the issue for you and close the issue if it does. If it doesn't please give a reproducible, self-contained example. If you want to cite other code, please provide a reference/link to the exact place this code has been cited from.

**Comment by thediveo** [comment] 2022-08-20 09:06
Closing this issue as resolved; please feel free to reopen with new information.

**Closed** 2022-08-20 09:08 UTC
Labels: waiting-for-response
