### ISSUE TITLE
please tag new release

### ISSUE THREAD

**Issue by onlyjob** [onsi/gomega#144] opened 2016-04-02 17:20 UTC
Latest release 1.0 was a while ago and now more and more Go applications vendor unreleased post-1.0 snapshots of _ginkgo_ and _gomega_ due to multiple fixes and improvements.

New release would be very helpful. Thanks.

**Comment by robdimsdale** [comment] 2016-04-27 02:07
@onlyjob I will let @onsi speak to this, but my interpretation is that we don't have release versions because all commits are good so you can safely use the latest SHA.

Specific releases would provide clarity, I agree, but is there a more specific problem you're looking to solve?

**Comment by onlyjob** [comment] 2016-04-27 09:44
Are you saying that we should disregard tagged versions and rely on latest snapshot?
Versioning is actually useful.

Tags/releases are useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Versioning provides additional benefits to encourage vendoring of a particular (e.g. latest stable) release contrary to random unreleased snapshots.

Versioning provides safety margin for situations like "ops, we've made a mistake but reverted problematic commit in master". Presumably tagged version/release is better tested/reviewed than random snapshot of "master" branch.

See also

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning

**Comment by calebamiles** [comment] 2016-08-19 23:30
It's probably not a great idea for me to wade into this discussion but since it's several months old perhaps I can elaborate on the explanation of the omission of release versioning beyond the announcement that "Gomega is considered stable" by adding a single `1.0` release. It would be great to close this issue if you are satisfied @onlyjob.

This project is developed using  a Test Driven Design methodology such that all functional specs should have been written before any code which provides the implementation which should provide downstream consumer some degree of confidence in the correctness of the implementation (at least insofar as they would have been satisfied by any non-formal proof of correctness). The maintainers of this project are also committed to using Continuous Integration to find regressions before changes are shipped to downstream consumers; one could reasonably argue that a `develop -> master` branch promotion strategy could be used to help ally fears downstream consumers but I've seen compelling arguments on both side of that debate. 

Additionally since this project is written in Golang is subject to the general expectation that most users will add this library via `go get github.com/onsi/gomega` which adheres to the ["stable master" philosophy](http://zduck.com/2014/go-and-package-versioning/) which is the best that native language tooling provides. Personally I think of the Golang model be conceptually similar to how [SUSE  continuously builds their distribution](https://en.opensuse.org/Portal:Tumbleweed) based on a rolling collection of upstream packages.

In the wild, many people have discovered that pulling dependencies straight from master isn't what they want and I believe the [vendor work](https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit) hopes to provide tooling to allow developers who desire fixed "known good || works for me"  versions of software to bundle their own dependencies as they see fit.

Arguably it could be useful to see some sort of publicly visible roadmap for Gomega but since this project is maintained in everyone's free time, to the best of my knowledge, there isn't a dedicated product overlord to make sure any public road map was even remotely accurate.

If there is a particular issue or pain you have felt, @onlyjob please don't hesitate to raise an issue but I believe that this is likely a "won't fix" without very compelling evidence that the floating master strategy pushed by the Golang authors is inappropriate here. Thank you for using Ginkgo/Gomega and happy testing!

**Comment by onlyjob** [comment] 2016-08-20 12:22
I have neither time not patience to explain how Golang ecosystem promotes culture of ignorance and systematically abuses best practice in software engineering. :(
Continuous integration is not a substitute for versioning. Th latter is more about life cycle and maintainability. It is not possible to force everyone to constantly upgrade vendored library to latest snapshot while it breaks API all the time...
Vendoring by tag is important even for the sake of native Golang library management tools like gopkg.in, getgb.io, gophers, glide, etc. Here is some info:

 * http://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases
 * http://dave.cheney.net/2016/06/26/automatically-fetch-your-projects-dependencies-with-gb

**Comment by calebamiles** [comment] 2016-08-20 18:37
Thank you for your additional comments @onlyjob and I am certainly not going to argue that the standard Golang tooling is perfect but unfortunately it's the tooling we have. In my opinion versioning is designed to convey intent to downstream consumers; the intent in this case is that all commits past the 1.0 release are minor or patch versions of the 1.X branch. Incrementing the minor/patch/build version of this project would likely be done my a CI robot in any case which I do not believe communicates any additional intent beyond what we currently have since we are not ready for a "Gomega 2.0" release at this point. 

If there is a specific instance where API compatibility was broken past the 1.0 release marker please do file an issue for that instance as it would have been a violation of the stable master philosophy which this project attempts to conform to. I am also not, at least intentionally, suggesting that Continuous Integration is a replacement for versioning but it is a tool that this project uses to convey our intent to produce a stable master such that downstream consumers _may use_ standard tooling like `go get` to fetch or update a dependency on Gomega relatively safely. I am still waiting for the suggestions offered by Dave Chaney to be widely adopted such that the standard tooling is updated.

I wish you the best of luck in pushing for their adoption but I do not believe that this is the correct forum for a broader discussion of software release management for Golang projects. As this discussion does not seem to describe a particular point of pain with this project specifically I am going to close the issue. Thank you again for using Gomega and please feel free to open issues describing places where we have not been faithful in the commitment to not break master for downstream consumers.

**Closed by calebamiles** 2016-08-20 18:37 UTC

**Comment by onlyjob** [comment] 2016-08-21 00:58
FYI @TheTincho.

**Comment by TheTincho** [comment] 2016-09-25 17:52
Hey all,

I had missed this discussion. I am the maintainer for gomega/ginkgo in Debian.

Many times I don't ask for tags to be added to golang projects, because I know there is a big cultural disagreement there, and most of the time it is difficult to reach an agreement.

The releases, as @calebamiles correctly point out, are supposed to have some meaning, so I understand it feels silly to tag randomly. If master is assumed to be always correct, and never break apis, then versioning does not have much sense, as every commit should have a tag.

For Debian it is nicer to have proper releases, as much of our tooling knows how to detect new releases, easily integrate new changes, etc. But at the end of the day, the important thing about releases is API stability, breaking changes, etc.

In this particular case, it bit me that you have stopped tagging releases, as I did not update the package in months, assuming that the new release was just taking too long.. I will now remove the automatic release check and switch to git snapshots.

In any case, thanks to all for the explanations.

**Comment by paultag** [comment] 2016-09-25 17:57
Just for another datapoint from a debian developer - I agree 100% with @TheTincho - most of my upstreams (heck, even go projects I maintain!) don't have releases at all, it's easier if they exist, but no biggie if they don't.

It's super fucking sad to read the tone taken in this report.

**Comment by onsi** [comment] 2016-09-25 21:12
HI all,

For both Ginkgo and Gomega I had aspirations - back when I had much more time on my hands - to manage a roadmap and meaningfully tag releases.  As my work responsibilities have ramped up I haven't been able to do this :/

Ginkgo and Gomega's current "contract" is to maintain backward compatibility on master.  Always.  Sadly, it's the most I can manage at this point.  If we ever do need to break compatibility we'll be sure to rev the major version but I do not have any known reasons for doing this at this point (except *maybe* to rip out the protobuf matcher).

@TheTincho sorry that this bit you.  Do you have any recommendation on how to communicate the contract (go with master, ignore the tags) more explicitly?

**Comment by TheTincho** [comment] 2016-09-26 15:07
Hi @onsi, thanks for the insight.

Don't worry about this too much, it is just a minor inconvenience. It would probably be a good idea to communicate this more obviously for other people, but I can't think of anything more sophisticated than a paragraph in the README.
