### ISSUE TITLE
YAML matcher

### ISSUE THREAD

**Issue by craigfurman** [onsi/gomega#139] opened 2016-03-16 11:54 UTC
Hi Onsi,

@tomwhoiscontrary and I created a MatchYAML matcher, which is heavily inspired by MatchJSON. It's in a [private CF repo that you should have access to](https://github.com/pivotal-cf-experimental/kafka-example-service-adapter/blob/master/yamlmatcher/match_yaml_matcher.go). It has a dependency on gopkg.in/yaml.v2.

Would you be interested in including this in Gomega? If so we can PR it in.

**Comment by robdimsdale** [comment] 2016-03-16 14:24
@craigfurman @tomwhoiscontrary thanks for doing this! I know it'll be useful.

There is some pain around ginkgo/gomega pulling in dependencies, see #114 and #123, so I'm not sure adding another dependency is a path we want to go down.

If you are willing to extract the matcher into its own (publically-available) repo, update the gomega docs to point to it, and add me as a maintainer, I would be happy to help out.

Thanks for doing this,
Rob

**Comment by craigfurman** [comment] 2016-03-18 07:22
Sounds good. We've created a chore
<https://www.pivotaltracker.com/story/show/115919467> in our private
tracker to do this

**Comment by tinygrasshopper** [comment] 2016-03-21 10:14
@robdimsdale It seems a bit odd to me to have a separate repo with one matcher.

Suggestion, could we have a separate package for the matchers requiring external dependencies.
It might look like:
`gomega/matchers/extensions/yaml`
`gomega/matchers/extensions/protobuf`

The difference between the extended matchers and the normal matchers, they wont be included in the `gomega/matchers.go`, so they wont be fetched when the user invokes `go get github.com/onsi/gomega`. If someone would like to use one of the extended matchers, they would have to fetch it by `go get gomega/matchers/extensions/yaml`

On the same lines as `ginkgo/extensions/table`.

What do you think?

**Comment by robdimsdale** [comment] 2016-03-21 13:32
@tinygrasshopper I think that proposal also works. Essentially I think the issue I'm looking to avoid is having 3rd-party dependencies imported from the root package, either directly or transitively, as this requires `go get github.com/onsi/gomega/...` rather than simply `go get github.com/onsi/gomega`.

I agree that splitting matchers across multiple repos is no ideal as it increases the cost of discovery. Your suggestion seems to be a good compromise this and the problem of introducing a new dependency.

We can't move the `protobuf` without making a breaking change (see #123) but we have the freedom to choose where new dependencies go. I like the idea of leveraging the `extensions` package like we do with `ginkgo`.

@onsi what are your thoughts?

**Comment by onsi** [comment] 2016-05-13 05:05
I'm not sure I have a strong opinion.... sequestering things into an `extensions` folder sounds fine to me.  the other option was to say "it's ok for gomega to pull in 3rd party dependencies, the problem is that `go get github.com/onsi/gomega` doesn't work" and we could solve that problem by doing `_` imports of the relevant packages in the root `gomega` package...

thoughts?

**Comment by tinygrasshopper** [comment] 2016-05-13 23:05
I think it is fair for a library like gomega to pull in 3rd party dependencies when it installs. 

I just realized, matchers that live in the `gomega/matchers` package wont face the issue of `go get github.com/onsi/gomega` not working, as `gomega/matchers` is referenced from the [root package](https://github.com/onsi/gomega/blob/master/matchers.go#L6), so go get can recursively fetch dependencies.

On the same lines, the issue mentioned in #123, I think the underlying problem is [the matcher](https://github.com/onsi/gomega/blob/master/ghttp/handlers.go#L155-L179) is written in the ghttp package rather than the matchers package, if the protobuf matcher was in the matchers package, go get should work.

**Comment by tinygrasshopper** [comment] 2016-05-16 15:12
We have updated #141 #142, to move the matcher from extensions to the matchers package. Tested the go get issue on local, if we `go get .` in the gomega directory it pulls in the yaml dependency. Do we see any issues with them merged? 

cc: @mariantalla

**Comment by robdimsdale** [comment] 2016-05-16 15:36
@tinygrasshopper you're saying the difference is that `matchers` doesn't use protobuf directly, but rather only in `ghttp`, whereas because this `yaml` matcher is references directly from the root it's fine?

Assuming you can `rm -rf $GOPATH/src/gopkg.in/yaml.v2` and then `go get -u github.com/onsi/gomega` and it repopulates `gopkg.in/yaml.v2`, then this is great and we don't need to worry about the `extensions` package.

I wonder if we can sidestep the `protobuf` issue by also making a `protobuf` matcher in the root package?

**Comment by tinygrasshopper** [comment] 2016-05-16 17:46
@robdimsdale yes, `go get ` fetches the package's dependencies, including the transitive ones, so as long as the package is present in the dependency tree it would be fetched. We did try it out on local. 

For the `protobuf` issue, I was planning to resolve it by extracting [this bit](https://github.com/onsi/gomega/blob/master/ghttp/handlers.go#L167-176) as a matcher named MatchProtobuf, and use it in `ghttp` just like MatchJSON, but will do that in a different PR.

The PR's related to this issue are ready to be merged I think.

**Comment by robdimsdale** [comment] 2016-05-16 17:54
I agree. Having side-stepped the question of the transitive `go-yaml` dependency, I see no reason not to merge #141 and #142 

I like the proposal to extract the `protobuf` matcher, and I agree it's a different PR.

**Comment by onsi** [comment] 2016-05-16 18:22
I like this plan






On Mon, May 16, 2016 at 10:54 AM -0700, "Rob Dimsdale" <notifications@github.com> wrote:












I agree. Having side-stepped the question of the transitive go-yaml dependency, I see no reason not to merge #141 and #142 



I like the proposal to extract the protobuf matcher, and I agree it's a different PR.

**Comment by tinygrasshopper** [comment] 2016-05-16 22:27
👍

**Closed by tinygrasshopper** 2016-05-16 22:27 UTC
